language: python

sudo: false

cache:
  - pip

python:
 - "2.7"
 - "3.5"

env:
 - DJANGO_VERSION=1.8.14
 - DJANGO_VERSION=1.9.9
 - DJANGO_VERSION=1.10

install:
 # Testing dependencies
 - pip install .[test]
 # The version of Django being tested against
 - pip install -q Django==$DJANGO_VERSION

script:
 - flake8 bakery
 - coverage run setup.py test

after_success:
 - coveralls
